#!/usr/bin/env python3
"""Generate docs/MAP.md: every function/section in core/ and topics/ with line numbers.

Agents grep this file and read only the line range they need instead of whole files.
Run after editing code (tools/verify.py runs it automatically).
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAT = re.compile(r'^\s*(?:function\s+(\w+)\s*\(|(?:const|let|var)\s+(\w+)\s*=\s*(?:\([^)]*\)|\w+)\s*=>|(?:const|let|var)\s+(\w+)\s*=\s*function|(\w+)\s*\([^)]*\)\s*\{\s*$|//\s*(?:={3,}|-{3,})\s*(.+?)\s*(?:={3,}|-{3,})?$)')
SKIP = {'if', 'for', 'while', 'switch', 'catch', 'function', 'return'}

def entries(path):
    out = []
    for n, line in enumerate(path.read_text().splitlines(), 1):
        m = PAT.match(line)
        if not m: continue
        name = next((g for g in m.groups()[:4] if g), None)
        if name and name not in SKIP:
            indent = len(line) - len(line.lstrip())
            if indent <= 6: out.append((n, name + '()'))
        elif m.group(5):
            out.append((n, '# ' + m.group(5)))
    return out

def main():
    lines = ['# Code map (generated by tools/mapgen.py, do not edit)', '',
             'Read a range with `sed -n START,ENDp FILE`. Regenerate: `python3 tools/mapgen.py`.', '']
    for path in sorted(list((ROOT / 'core').glob('*.js')) + list((ROOT / 'topics').glob('*.js'))):
        if path.name.endswith('.design.js'): continue
        total = sum(1 for _ in path.open())
        lines.append(f'## {path.relative_to(ROOT)} ({total} lines)')
        for n, name in entries(path): lines.append(f'- {n}: {name}')
        lines.append('')
    (ROOT / 'docs/MAP.md').write_text('\n'.join(lines))
    print(f'wrote docs/MAP.md ({len(lines)} lines)')

if __name__ == '__main__':
    main()
